services:
  - type: web
    name: roblox-landing-page
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roblox-db
          property: connectionString
      - key: DB_SSL
        value: "true"

databases:
  - name: roblox-db
    plan: free
